name: Refresh Repository Test
on:
  workflow_dispatch:

jobs:
  RefreshAddon_leia_1:
    permissions:
      contents: write
    uses: ./.github/workflows/refreshKodiAddon.yml
    with:
      target_app_owner: "codingPF"
      target_app: "script.module.ckfw"
      target_app_branch: "main"
      target_kodi_version_name: "nexus"
      target_kodi_python_version: "3.0.0"
